druid:
  datasource:
    default:
      username: root
      password: root
      url: jdbc:mysql://192.168.99.100:3306/mywork?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
logging:
  config: classpath:log4j2.xml

email:
  smtp:
    host: smtp.126.com
  send:
    from: liliang988@126.com
  auth:
    code: xxxxxx


